name: newton-car-maintenance-php-assignment
recipe: lamp
config:
  php: '8.2'


proxy:
  # Set Magento URL
  appserver-main:
    - newton-car-maintenance.lndo.site
  external-spare-part-api:
    - external-spare-part-api.lndo.site 

services:
  appserver-main:
    type: php:8.2
    webroot: public
    via: apache
    build_as_root:
      - 'composer install'
      - 'php bin/console doctrine:migrations:migrate'

  database-main:
    type: mysql:5.7 
    portforward: true
    creds:
      database: newton_car_maintenance
      user: newton_car_maintenance
      password: newton_car_maintenance

  external-spare-part-api:
    type: php:8.2
    webroot: externalSparePartsAPI/public
    via: apache
    build_as_root:
      - 'composer install'
      - 'php bin/console doctrine:migrations:migrate'

  
  external-spare-part-api-database:
    type: mysql:5.7 
    portforward: true
    creds:
      database: external_spare_part_api
      user: external_spare_part_api
      password: external_spare_part_api

tooling:
  console-main:
    service: appserver-main
    description: Run Symfony console commands
    cmd: 'php bin/console'

  console-external-spare-part-api:
    service: external-spare-part-api
    description: Run Symfony console commands
    cmd: 'php bin/console'



